version: "3.9"

services:
  ubuntukvm:
    build: .
    container_name: ubuntukvm
    stdin_open: true
    tty: true
    privileged: true
    devices:
      - /dev/kvm:/dev/kvm
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    ports:
      - 3389:3389
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    environment:
      - MEMORY=${MEMORY}
      - CPU=${CPU}
      - DISK_SIZE=${DISK_SIZE}
    cgroup: host